### ISSUE TITLE
Move EF6 to ASP.NET Core build environment

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#612]
As part of this ensure that:
- [x] NuGet packages are signed: #611 
- [x] NuGet packages have correct copyright info: #610 
- [x] SourceLink is handled appropriately: #514
